### ISSUE TITLE
[RFE] upgrade coreos-base/afterburn

### ISSUE THREAD

**Issue by tormath1** [kinvolk/Flatcar#1049]
## Current situation

Flatcar is currently running the version 5.2.0 while the 5.4.2 is out and soon a new release should bring the following patch: https://github.com/coreos/afterburn/pull/931 which is required for CAPO (Cluster API OpenStack) project (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1564)

## Implementation options

* There is a few patches to port (https://github.com/flatcar/scripts/blob/b5dbef8d2bff97953ac9f27a431696280a2244bb/sdk_container/src/third_party/coreos-overlay/coreos-base/afterburn/afterburn-9999.ebuild#L223-L227)
* Generate with `cargo-ebuild` the new dependencies list

## Additional information

Have a look to the afterburn changelog (https://github.com/coreos/afterburn/compare/v5.2.0...v5.4.2)

EDIT: Discussed with @mdbooth during CAPO office hours: "what would be the best way to have the upgrade into Flatcar" - I see two options:
* backport the upgrade to all channels (including Stable) (not a big fan of bypassing the usual channel validation)
* as the upgrade does not seem to be a big upgrade, we could backport it to Alpha / Beta only and change the Flatcar image to Beta for the CAPO CI

Here's the CAPO PR: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1564

**Comment by dongsupark** [comment]
+1 for the 2nd option, "backport it to Alpha / Beta only and change the Flatcar image to Beta for the CAPO CI".

**Comment by tormath1** [comment]
Aftberburn 5.5.0 is out: https://github.com/coreos/afterburn/releases/tag/v5.5.0
