### ISSUE TITLE
mantle: DigitalOcean image removal

### ISSUE THREAD

**Issue by pothos** [kinvolk/Flatcar#1065]
## Description

Somehow our kola tests ended up creating same-named images, and `ore do delete-image --name=` can't delete them if more than one exists.

## Impact

Tests can't be run and we scatter the images.
Not sure if even the garbage collection is affected.

**Comment by tormath1** [comment]
Reading the code, we don't support having multiple images with the same name: https://github.com/flatcar/mantle/blob/09cf13abdf03500ba64e93236c24874d189eda5a/platform/api/do/api.go#L287-L289

Some ideas:
* ignore this as it's the first time we see such an issue?
* support multiple images having the same name and return a slice of IDs.
* prevent image creation if an image already exist with the same name

**Comment by sayanchowdhury** [comment]
This quite happens during the release, I usually use delete both the images using `doctl` and start the new job.

**Comment by tormath1** [comment]
Thanks @sayanchowdhury for bringing this information. In this case, as the DigitalOcean API seems to support having two images with the same name, I think we can follow this design and implement the following option: "support multiple images having the same name and return a slice of IDs to delete.". What do you think ?
