### ISSUE TITLE
[RFE] Document built-in Systemd sysext images

### ISSUE THREAD

**Issue by tormath1** [kinvolk/Flatcar#1409]
## Current situation

Currently, there is no documentation on how to use the built-in Sysext images except some Butane snippet or sharing configuration used in the CI.

## Impact

It makes harder to discover the existing images and how to easily deploy them on Flatcar.

## Ideal future situation

Supported extensions listed in the documentation + Butane / Ignition example to deploy it + a simple example to get started with the extension: if it takes some specific additional configuration, etc. 

## Implementation options

It could be under the "Provisioning Tools > Systemd sysext" section.

* Docker 
* Containerd
* ZFS
* Incus

## Additional information

n/a

**Comment by t-lo** [comment]
Great idea, we could also make this section more generalised about "extending the base OS system" (if only by header, for a start). The bakery also offers pre-baking images, we should cover this too: https://github.com/flatcar/sysext-bakery/?tab=readme-ov-file#baking-sysexts-into-flatcar-os-images

**Comment by pothos** [comment]
The new section on Flatcar release extensions: https://www.flatcar.org/docs/latest/provisioning/sysext/#flatcar-release-extensions
Mentioning of the pre-baking of images: https://www.flatcar.org/docs/latest/provisioning/sysext/#bundle-extensions-in-a-flatcar-image
