### ISSUE TITLE
sudo fails for ldap users

### ISSUE THREAD

**Issue by fbsb** [kinvolk/Flatcar#471]
## Description
 
After updating to latest stable v2905.2.0 sudo fails for LDAP users using sssd. The problem seems to have been introduced by https://github.com/kinvolk/baselayout/pull/17

## Impact

LDAP users could not elevate privileged with sudo after logging in to ssh with public keys.

## Environment and steps to reproduce

1. configure sssd with ldap
2. login to ssh via public key
3. elevate privilege using e.g. `sudo -i`
4. sudo fails with correct password

## Expected behavior

sudo should succeed when password is correct

## Additional information

Moving `pam_faillock.so` after `pam_sss.so` fixes the issue and sudo works as expected.

```
auth		required	pam_env.so
auth		requisite	pam_faillock.so preauth deny=5 unlock_time=60 fail_interval=120
auth		sufficient	pam_unix.so try_first_pass likeauth nullok
auth		sufficient	pam_sss.so use_first_pass
# give pam_sss a chance to authenticate ldap users
auth		[default=die]	pam_faillock.so authfail deny=5 unlock_time=60 fail_interval=120
auth		required	pam_deny.so

account		required	pam_unix.so
# Don't fail if the user is unknown to sssd or if sssd isn't running
account		required	pam_sss.so ignore_unknown_user ignore_authinfo_unavail
account		required	pam_faillock.so
account		optional	pam_permit.so

password	sufficient	pam_unix.so try_first_pass nullok sha512 shadow minlen=8
password	sufficient	pam_sss.so use_authtok
password	required	pam_deny.so

session		required	pam_limits.so
session		required	pam_env.so
session		required	pam_unix.so
session		optional	pam_permit.so
session		optional	pam_sss.so
-session        optional        pam_systemd.so
```

**Comment by pothos** [comment]
Hi,

thanks for your detailed report and the fix, I started a PR here: https://github.com/kinvolk/baselayout/pull/18

**Comment by pothos** [comment]
The fix will be part of all future releases (>  2905.2.1, > 2942.1.0, >  2955.0.0)
