### ISSUE TITLE
flatcar 2905.2.2 is missing setfacl(1)

### ISSUE THREAD

**Issue by stapelberg** [kinvolk/Flatcar#488]
## Description

flatcar 2905.2.2 is missing the `acl` package binaries, specifically `setfacl(1)` and `getfacl(1)`. These were included in previous versions.

## Impact

I use filesystem ACLs to grant access to SSL certificate files to different uids within docker containers.

Without `setfacl(1)`, my SSL certificate setup is broken (I noticed due to the certificate expiration alerts firing).

## Environment and steps to reproduce

1. **Set-up**: n/a
2. **Task**: Updating SSL certificates
3. **Action(s)**: `setfacl -m u:99:r /persistent/ssl/newcert.crt`
4. **Error**: `bash: setfacl: command not found`

## Expected behavior

`setfacl(1)` should be available.

**Comment by stapelberg** [comment]
Aside from the longer-term fix, I’m curious if there’s any workarounds?

**Comment by tormath1** [comment]
Hi @stapelberg, 

Indeed `sys-apps/acl` has been removed from the OS when we [dropped](https://github.com/kinvolk/coreos-overlay/pull/965/files) the `rkt` container runtime - it was a dependency of this package.

As a temporary workaround, you can try to use `setfacl` from [Commando](https://github.com/lukaszlach/commando) Docker image:

```shell
$ docker run -v "/persistent/ssl/newcert.crt:/opt/newcert.crt" cmd.cat/setfacl setfacl -m u:99:r /opt/newcert.crt
$ docker run -v "/persistent/ssl/newcert.crt:/opt/newcert.crt" cmd.cat/getfacl getfacl /opt/newcert.crt
getfacl: Removing leading '/' from absolute path names
# file: opt/newcert.crt
# owner: root
# group: root
user::rw-
user:99:r--
group::r--
mask::r--
other::r--
```

Let us know how it goes !

EDIT: a PR has been opened to explicitly add `sys-apps/acl` to Flatcar dependencies (https://github.com/kinvolk/coreos-overlay/pull/1240) - thanks for your report !

**Comment by tormath1** [comment]
Hi @stapelberg , `sys-apps/acl` will be available in the next alpha release and it should include the `setfacl` and `getfacl` binaries.

I hope the workaround will help you and thanks for reporting this!

**Comment by stapelberg** [comment]
Thanks for getting this fixed so quickly and for sharing the workaround!
