### ISSUE TITLE
Incorrect path to amazon-ssm-agent in base-ec2.ign

### ISSUE THREAD

**Issue by a-wh** [kinvolk/Flatcar#489]
## Description

The ExecStart path for amazon-ssm-agent.service in [base-ec2.ign](https://github.com/kinvolk/coreos-overlay/edit/main/coreos-base/oem-ec2-compat/files/base/base-ec2.ign) is incorrect. It is defined as `/usr/share/oem/amazon-ssm-agent` but should be `/usr/share/oem/bin/amazon-ssm-agent`.

```
# ls -lahrt /usr/share/oem/amazon-ssm-agent
ls: cannot access '/usr/share/oem/amazon-ssm-agent': No such file or directory

# ls -lahrt /usr/share/oem/bin/amazon-ssm-agent
-rwxr-xr-x. 1 root root 31M Aug 18 01:28 /usr/share/oem/bin/amazon-ssm-agent
```

## Impact

AWS SSM Agent fails to start

## Environment and steps to reproduce

1. **Set-up**: Flatcar 2969.0.0 (Alpha) on AWS 
2. **Task**: Boot from image
3. **Action(s)**: N/A
4. **Error**: aws-ssm-agent systemd service fails to start due to incorrect path

## Expected behavior

aws-ssm-agent should start

**Comment by a-wh** [comment]
I've created a PR for this one: https://github.com/kinvolk/coreos-overlay/pull/1228

**Comment by jepio** [comment]
Awesome catch, we only managed to get the amazon-ssm-agent into the image very recently and we don't have tests for it yet.

I merged the PR :)

**Comment by jepio** [comment]
@a-wh I have an additional question: we currently ship amazon-ssm-agent-2.3.1319. Do you think it's worth updating?
