### ISSUE TITLE
[RFE] move FIPS enablement into mainline builds of Flatcar

### ISSUE THREAD

**Issue by vbatts** [kinvolk/Flatcar#537]
## Current situation

only Flatcar LTS has FIPS enablement for Linux Kernel and cryptsetup, with OpenSSL planned.
With Flatcar being completely a community project, this enablement should be in the mainline builds.

## Ideal future situation

It will allow broader community access and testing to all features.
Simplified build paths for all channels/streams.

**Comment by tormath1** [comment]
PR has been opened and merged upstream to bring `FIPS` support to `dev-libs/openssl`: https://github.com/gentoo/gentoo/pull/22796

EDIT: `FIPS` module is now built-in in Flatcar: https://github.com/flatcar-linux/coreos-overlay/pull/1389

**Comment by pothos** [comment]
Missing is adding `--enable-fips` for `sys-fs/cryptsetup` and the kernel config. I'll open a PR for the kernel (Edit: done in https://github.com/flatcar-linux/coreos-overlay/pull/1602) but for cryptsetup we first need a Gentoo useflag.

**Comment by vbatts** [comment]
This is something we will bring over from the LTS build, right?

**Comment by tormath1** [comment]
> Missing is adding `--enable-fips` for `sys-fs/cryptsetup` and the kernel config. I'll open a PR for the kernel (Edit: done in [flatcar-linux/coreos-overlay#1602](https://github.com/flatcar-linux/coreos-overlay/pull/1602)) but for cryptsetup we first need a Gentoo useflag.

@pothos issue has been opened upstream to ask for `fips` useflag for cryptsetup: https://bugs.gentoo.org/834920 and PR has been opened too - let's see if it goes accepted.

**Comment by tormath1** [comment]
Upstream PR has been merged - let's enable FIPS in the OS:
- https://github.com/flatcar-linux/portage-stable/pull/311
- https://github.com/flatcar-linux/coreos-overlay/pull/1747
