### ISSUE TITLE
The "flatcar_production_qemu.sh" script does not work with darwin (MacOS)

### ISSUE THREAD

**Issue by martinborgman** [kinvolk/Flatcar#749]
## Description

In the version of the script that uses the VM_NAME flatcar_production_qemu-3139-2-1, there are currently two issues that make it fail to start the vm on darwin.

## Impact

The "flatcar_production_qemu.sh" script does not work with darwin (MacOS)

## Environment and steps to reproduce

Darwin macpro 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
QEMU emulator version 6.2.0

The script crashes at mktemp because the script uses the GNU enhanced mktemp syntax however in most cases, as in this one, using the GNU enhanced syntax is unnecessary.

The second problem is shown after you fix the first problem and occurs when qemu-system-x86_64 gives an error because darwin doesn't use a linux kernel and therefore doesn't support the kvm accelerator. There is however an accelerator for darwin called hvf which works fine with the provided flatcar image.

## Expected behavior

I expected the script to work on darwin

## Additional information

If I could find the "flatcar_production_qemu.sh" script on github I would have made a PR instead.

The suggested fix for the mktemp problem is:
```shell
if [ -z "${CONFIG_IMAGE}" ]; then
    CONFIG_DRIVE=$(mktemp -d -t 'flatcar-configdrive')
    ret=$?
```

The suggested fix for the qemu-system-x86_64 accelerator problem is:
```shell
    case "${VM_BOARD}+$(uname -m)" in
        amd64-usr+x86_64)
            # Emulate the host CPU closely in both features and cores.
            set -- -machine accel=kvm:hvf -cpu host -smp "${VM_NCPUS}" "$@" ;;
```

I hope this helps

**Comment by jepio** [comment]
I tried this a couple of months ago, and came up with the following diff https://github.com/flatcar-linux/scripts/compare/jepio/qemu-script-support-mac, but `accel=kvm:hvf` looks better. Did you have an issue with the configdrive? I also noticed `nproc` was missing by default, but that can be solved by installing something (coreutils).

Any chance you have an M1 Mac to test the aarch64 version?

**Comment by martinborgman** [comment]
Yes, I did have an issue with configdrive due to the GNU mktemp syntax used in the script. I suggested a fix for this issue by using the POSIX standard syntax of mktemp.

I did not have an issue with `nproc` though but I see it is in my homebrew directory, so I checked, I have coreutils installed.

I do have access to a M1 Pro Mac so I can test the aarch64 version. I also have QEMU version 7 now. I will try and test both this coming weekend.

**Comment by martinborgman** [comment]
Looking at our `nproc` problem, I found this article https://stackoverflow.com/questions/45181115/portable-way-to-find-the-number-of-processors-cpus-in-a-shell-script. MacOS however does have `getconf` so `getconf _NPROCESSORS_ONLN` should work on both Linux an MacOS.

**Comment by martinborgman** [comment]
So far flatcar works fine with qenu 7.0.0 on macOS x86_64.
Running the flatcar aarch64 version on M1 is i different story. I have to dig a little deeper into UEFI on qemu.

**Comment by jepio** [comment]
Would you be able to open up a PR to flatcar-linux/scripts with the necessary changes? We could get x86_64 reviewed/merged first and aarch64 later.

**Comment by martinborgman** [comment]
Will do.

I will make a different issue for aarch64 because emu-system-aarch64 requires te code and vars file to be 64M. I still couldn't boot flatcar aarch64 though.

However flatcar x86_64 does run on an M1.

**Comment by martinborgman** [comment]
Unfortunately I do not have permissions to create a PR but this is my diff:

```
diff --git a/build_library/qemu_template.sh b/build_library/qemu_template.sh
index 48c82dbf..6c2f2805 100755
--- a/build_library/qemu_template.sh
+++ b/build_library/qemu_template.sh
@@ -11,7 +11,7 @@ VM_MEMORY=
 VM_CDROM=
 VM_PFLASH_RO=
 VM_PFLASH_RW=
-VM_NCPUS="$(nproc)"
+VM_NCPUS="$(getconf _NPROCESSORS_ONLN)"
 SSH_PORT=2222
 SSH_KEYS=""
 CLOUD_CONFIG_FILE=""
@@ -111,7 +111,7 @@ write_ssh_keys() {


 if [ -z "${CONFIG_IMAGE}" ]; then
-    CONFIG_DRIVE=$(mktemp -t -d flatcar-configdrive.XXXXXXXXXX)
+    CONFIG_DRIVE=$(mktemp -d -t flatcar-configdrive)
     ret=$?
     if [ "$ret" -ne 0 ] || [ ! -d "$CONFIG_DRIVE" ]; then
         echo "$0: mktemp -d failed!" >&2
@@ -156,7 +156,7 @@ else
     case "${VM_BOARD}+$(uname -m)" in
         amd64-usr+x86_64)
             # Emulate the host CPU closely in both features and cores.
-            set -- -machine accel=kvm -cpu host -smp "${VM_NCPUS}" "$@" ;;
+            set -- -machine accel=kvm:hvf:tcg -cpu host -smp "${VM_NCPUS}" "$@" ;;
         amd64-usr+*)
             set -- -machine pc-q35-2.8 -cpu kvm64 -smp 1 -nographic "$@" ;;
         arm64-usr+aarch64)

```

**Comment by pothos** [comment]
> Unfortunately I do not have permissions to create a PR but this is my diff:

Is there a problem at our end?

**Comment by martinborgman** [comment]
To create a PR you must be able to create a branch.

**Comment by pothos** [comment]
You can fork the project, clone your forked repo, and push a branch to your repo, then GitHub will print you a link that will create a PR.

**Comment by pothos** [comment]
Or the alternative is to use the web UI, by clicking the edit icon on this file: https://github.com/flatcar-linux/scripts/blob/main/build_library/qemu_template.sh

**Comment by martinborgman** [comment]
Thank you, pull request created

**Comment by krnowak** [comment]
With https://github.com/flatcar-linux/scripts/pull/348 being merged, this can be closed now.
