### ISSUE TITLE
flatcar-update - Error: update failed

### ISSUE THREAD

**Issue by cpswan** [kinvolk/Flatcar#758]
## Description

When running `sudo flatcar-update --to-version "3139.2.1"` the console output first shows:

```
Forcing update...
```

Which is great, but then:

```
Error: update failed
```

Without any further explanation of why the update failed, or what can be done to fix that.

I've also tried `sudo flatcar-update --to-version "3139.2.1" --to-payload /var/tmp/update_payload` but the outcome doesn't change.

## Impact

Preventing the update of patched 3139.2.0 nodes to 3139.2.1

## Environment and steps to reproduce

1. **Set-up**: `Flatcar Container Linux by Kinvolk stable 2022.04.07+dev-flatcar-master-5373 for Google Compute Engine`, which was created by @jepio to deal with #714 
2. **Task**: update to latest stable release
3. **Action(s)**:  `sudo flatcar-update --to-version "3139.2.1"`
4. **Error**: `Error: update failed`

## Expected behavior

Update is made ready, and takes place on next reboot.

If `flatcar-update` hits a problem it presents an error message that gives some clue about what should be done to remove that problem.

## Additional information

Running `sudo update_engine_client -status` I get:

```
I0530 15:38:14.290454  2224 update_engine_client.cc:241] Querying Update Engine status...
LAST_CHECKED_TIME=1653924489
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
```

Doing the same whilst `Forcing update...` shows gets:

```
I0530 15:39:01.214694  2382 update_engine_client.cc:241] Querying Update Engine status...
LAST_CHECKED_TIME=1653925138
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_UPDATE_AVAILABLE
NEW_VERSION=3139.2.1
NEW_SIZE=344544962
```

But once `Error: update failed` comes up, we're back to:

```
I0530 15:39:47.871093  2419 update_engine_client.cc:241] Querying Update Engine status...
LAST_CHECKED_TIME=1653925138
PROGRESS=0.000000
CURRENT_OP=UPDATE_STATUS_IDLE
NEW_VERSION=0.0.0
NEW_SIZE=0
```

**Comment by pothos** [comment]
The dev build image that you have installed doesn't use the production update signing key, thus I guess you'll find some error message about it in `journalctl -u update-engine`. The solution is to force using the production update signing key:

```
sudo flatcar-update --to-version "3139.2.1" --force-flatcar-key
```

**Comment by cpswan** [comment]
Thanks @pothos that did it, though many (most) of them needed:

```
sudo flatcar-update --to-version "3139.2.1" --force-flatcar-key --to-payload /var/tmp/update_payload
```

I'll open a fresh feature request suggesting the journalctl stuff be added to the error message.
