### ISSUE TITLE
journald: some issues with `--user` and persistency

### ISSUE THREAD

**Issue by tormath1** [kinvolk/Flatcar#989]
## Description

With recent `podman` experimentation involving systemd users unit, we started seeing some issues with journald, some of them can be fixed on the Flatcar side others not. This issue is for tracking and referencing purposes.

1. Permission issues:

Trying to display the journal with `--user` fails with:
```
core@localhost ~ $ journalctl --user
No journal files were opened due to insufficient permissions.
```

PR:
- https://github.com/flatcar/bootengine/pull/59
- https://github.com/flatcar/coreos-overlay/pull/2553
- https://github.com/flatcar/flatcar-docs/pull/297

2. Can't display the logs for a given unit with `--user`:

When creating a user unit, you can display logs of the unit with `systemctl --user status foo.service` or `journalctl --user-unit foo.service` but not with `journalctl --user --unit foo.service`. The is reported upstream: https://github.com/systemd/systemd/issues/26742 (see also: https://github.com/flatcar/flatcar-docs/pull/295)

That works fine by creating a user in the `systemd-journal` (doc: https://github.com/flatcar/flatcar-docs/pull/297)

3. First journal is not persisted:

Starting from alpha-3549.0.0, the first journal logs is not persisted: if you boot 2 times, you'll get only 1 journal entry.

We need to create /sysroot/var/log/journal with correct permissions to get it persisted.

PR:
- https://github.com/flatcar/bootengine/pull/60
- https://github.com/flatcar/coreos-overlay/pull/2558
- https://github.com/flatcar/baselayout/pull/29

**Comment by pothos** [comment]
All fixes are in, I think we can close this, assuming that the docs PR for user session logs gets merged

**Comment by tormath1** [comment]
Closing this. All fixes should be available in the next Alpha - thanks @pothos for helping on this topic!
